hyperledger-labs/blockchain-explorer

- CONTRIBUTING.md
- docs/source/CONTRIBUTING.rst
- docs/source/architecture/sync_configuration.rst
- docs/source/architecture/websockets.rst
- docs/source/dev-setup/devenv.rst
> BE-708 Online docs issues

- CONTRIBUTING.md
- README.md
- docs/source/CONTRIBUTING.rst
- docs/source/architecture/sync_configuration.rst
- docs/source/architecture/websockets.rst
- docs/source/dev-setup/devenv.rst
Fixed invalid link to readthedocs
> BE-708 Online docs issues 

- CONTRIBUTING.md
- README.md
- app/test/package-lock.json
- client/package-lock.json
- docs/source/CONTRIBUTING.rst
- docs/source/architecture/sync_configuration.rst
- docs/source/architecture/websockets.rst
- docs/source/dev-setup/devenv.rst
> BE-710 Security vulnerability

- app/platform/fabric/sync/SyncService.js
Added check to see if new channel is found.
> BE-713 Fix an issue to fail detecting newly added channel

- CHANGELOG.md
- README.md
- release_notes/v1.0.0-rc2.md
* release candidate v1.0.0-rc2
> BE-716 RC v1.0.0-rc2

- README.md
Added an update, that Explorer can work with Iroha now! 
Signed-off-by: Sara <lira.lemur@gmail.com>
> Added some information on HL Iroha support to README file

- docker-compose.yaml
This is due to explorer tries to connect to db before the db starts successfully.
> explorer exits due to ECONNREFUSED to port 5432

- app/platform/fabric/e2e-test/specs/apitest_def_test.go
- app/platform/fabric/e2e-test/specs/apitest_test.go
- app/platform/fabric/service/NetworkService.js
- client/src/components/Login/Login.js
- client/src/state/redux/auth/operations.js
- Hide username/password when the network does not have auth (addresses [BE-729](https://jira.hyperledger.org/browse/BE-729))
- Auto-login when there's one network without auth
> Fix enableAuthentication bug and enable auto-login

- app/rest/authroutes.js
- client/src/components/Header/HeaderView.js
- client/src/state/redux/auth/operations.js
* make logout button and auth function in client
* make logout rest api in platform
Signed-off-by: 5pecia1 <pdpxpd@gmail.com>
https://jira.hyperledger.org/browse/BE-733
> [BE-733] Implement logout

- TROUBLESHOOT.md
* append troubleshoot about not assigned to this channel
Signed-off-by: 5pecia1 <pdpxpd@gmail.com>
> Append troubleshoot about explorer failes to start

- app/platform/fabric/connection-profile/first-network.json
- app/platform/fabric/e2e-test/README.md
- app/platform/fabric/e2e-test/runTestSuite.sh
- app/platform/fabric/e2e-test/specs/apitest-network-spec.yml
- client/package-lock.json
- package-lock.json
- package.json
https://jira.hyperledger.org/browse/BE-734
> BE-734 Upgrade for fabric v1.4.6 support

- TROUBLESHOOT.md
Fix "Related Information" heading tag level 4 to 5 in TROUBLESHOOT.md file
Signed-off-by: 5pecia1 <pdpxpd@gmail.com>
> Fix "Related Information" heading tag level 4 to 5

- client/package-lock.json
- client/package.json
- package-lock.json
- package.json
upgraded react-script for remove vulnerability issue
dir: blockchain-explorer/client
npm audit
=== npm audit security report ===                        
found 0 vulnerabilities
in 945115 scanned packages
> BE 727 Security vulnerability in "react-scripts"

- README.md
https://jira.hyperledger.org/browse/BE-740
> BE-740 Update the document for multi-org

- app/platform/fabric/FabricClient.js
- app/platform/fabric/gateway/FabricGateway.js
- app/platform/fabric/sync/SyncPlatform.js
- app/platform/fabric/sync/SyncService.js
- package-lock.json
Stop using Channel class of fabric-client package to discovery peers in a channel.
Using discovery service class is recommended officially.
> BE-748 Change discovery service to make use of  DiscoveryService

- app/platform/fabric/gateway/FabricGateway.js
- app/platform/fabric/sync/SyncService.js
> Be 750 Implement queryInstantiatedChaincodes by using "getchaincodes" func on LSCC

- .sonarcloud.properties
- README.md
https://sonarcloud.io/dashboard?id=hyperledger_blockchain-explorer
> Fix configuration for SonarCloud and add badge

- app/test/package-lock.json
- app/test/postgrespgtest.js
- ci/azure-pipelines.yml
- docker-compose-testdb.yaml
We also need to fix error of postgrespgtest.js. The test is always failing on CI pipeline because postgres db doesn't exist.
https://jira.hyperledger.org/browse/BE-759
> BE-759 Fix vulnerability of package under api/test

- app/platform/fabric/Proxy.js
- app/platform/fabric/gateway/FabricGateway.js
- app/platform/fabric/sync/SyncService.js
- app/platform/fabric/utils/FabricUtils.js
- app/rest/platformroutes.js
- package-lock.json
Needed to fix some incompatible issues
https://jira.hyperledger.org/browse/BE-766
> BE-766 Update fabric-sdk-node to v2.1.1

- CODEOWNERS
- README.md
> updated readme document

- README.md
- app/platform/fabric/connection-profile/first-network.json
- docker-compose.yaml
- examples/net1/connection-profile/first-network.json
- start.sh
Preview: https://github.com/nekia/blockchain-explorer/tree/simplify-readme
> BE-772 Make the landing page on Github simplified

- app/platform/fabric/e2e-test/specs/apitest_test.go
- app/platform/fabric/e2e-test/specs/validate_hash.sh
- app/platform/fabric/utils/FabricUtils.js
Also added test for validating hash chain
https://jira.hyperledger.org/browse/BE-776
> BE-776 Fix calculation of block hash

- CHANGELOG.md
- README.md
- client/package.json
- package.json
- release_notes/v1.1.1.md
https://jira.hyperledger.org/browse/BE-775
> BE-775 Release v1.1.1

- .eslintrc.json
- client/.eslintrc.json
- client/src/components/View/TransactionView.js
https://jira.hyperledger.org/browse/BE-778
> BE-778 Fix typo tx detail view

- app/platform/fabric/sync/SyncService.js
https://jira.hyperledger.org/browse/BE-780
> BE-780 Fixed typos in "SyncService"

- app/platform/fabric/e2e-test/specs/apitest_test.go
- app/platform/fabric/service/UserService.js
https://jira.hyperledger.org/browse/BE-782
> BE-782 Adjust register API to use the new user model

- .eslintrc.json
- app/model/User.js
- app/persistence/fabric/postgreSQL/db/explorerpg.sql
- app/platform/fabric/rest/adminroutes.js
- app/platform/fabric/service/UserService.js
- client/src/components/Register/Register.js
Added the following input form:
* Password(confirm)
* First name(optional)
* Last name(optional)
* E-mail(optional)
'Affiliation' was deleted.
https://jira.hyperledger.org/browse/BE-783
> BE-783 Update User registration UI

- client/package-lock.json
> Fix Security vulnerability

- app/platform/fabric/e2e-test/configs/connection-profile/org1-network.json
- app/platform/fabric/e2e-test/configs/connection-profile/org2-network.json
- app/platform/fabric/e2e-test/specs/apitest_test.go
- app/platform/fabric/e2e-test/specs/apitest_utils_test.go
> BE-784 Add e2e test for Web API of user management

- app/platform/fabric/sync/SyncService.js
https://jira.hyperledger.org/browse/BE-803
Resolves #159
> BE-803 Correct index to get validation code from metadata

- client/package-lock.json
> BE-804 Fix Security vulnerability

- CHANGELOG.md
- README.md
- client/package.json
- package.json
- release_notes/v1.1.2.md
> BE-802 Release v1.1.2

- client/package-lock.json
> BE-813 Fixed security vulnerability issues

- MAINTAINERS.md
> updated maintainer name

- client/package-lock.json
> BE-819 Security Vulnerability - Upgraded bl version

- .eslintrc.json
- README.md
- app/Explorer.ts
- app/platform/PlatformBuilder.ts
- app/platform/fabric/FabricConfig.js
- app/platform/fabric/e2e-test/specs/runexplorer.sh
- app/platform/fabric/e2e-test/specs/stopexplorer.sh
- client/e2e-test/specs/root.js
- main.ts
- package-lock.json
- package.json
- start.sh
- tsconfig.json
> BE-769 Initial migration

- client/package-lock.json
> BE-827-security-vulnerability Updated node-forge

- app/sync/SyncBuilder.ts
- app/sync/listener/ExplorerListener.ts
- app/sync/listener/ForkListenerHandler.ts
- app/sync/sender/ExplorerSender.ts
- app/sync/sender/ForkSenderHandler.ts
> BE-822 Converted javascript to typescript

- app/Explorer.ts
- app/common/ExplorerError.ts
- app/common/ExplorerMessage.ts
- app/rest/dbroutes.ts
- client/src/FabricVersion.js
- client/src/components/Container.js
- client/src/components/Footer/FooterView.js
- client/src/components/Header/HeaderView.js
- client/src/components/Lists/Blocks.js
- client/src/components/Lists/Chaincodes.js
- client/src/components/Lists/Channels.js
- client/src/components/Lists/Peers.js
- client/src/components/Lists/Transactions.js
- client/src/components/Lists/Users.js
- client/src/components/Panels/NotificationsPanel.js
- client/src/components/Register/Register.js
- client/src/components/UsersPanal/UsersPanal.js
- client/src/static/css/main-dark.css
- client/src/static/css/main.css
> BE-835 Fixed sonarcloud code smell issues

- app/platform/fabric/sync/SyncService.ts
As explained on JIRA BE-839
Signed-off-by: sigma67 <benedikt.putz@wiwi.uni-regensburg.de>
> BE-839 Fix transaction creator certificate sync

- app/platform/fabric/gateway/FabricGateway.ts
This log print error's JSON struct with ERROR_1010
Signed-off-by: Sol Kang <pdpxpd@gmail.com>
> BE-842 Change to useful log in initialize

- app/platform/fabric/FabricConfig.ts
- app/platform/fabric/gateway/FabricGateway.ts
This is to fix https://jira.hyperledger.org/browse/BE-847
> [BE-847] Single Line TLSCA Cert PEM in CA

- app/platform/fabric/Proxy.ts
- app/platform/fabric/sync/SyncService.ts
- client/e2e-test/specs/dashboard/dashboard.js
- client/e2e-test/specs/network/network_view.js
https://jira.hyperledger.org/browse/BE-829
> BE-829 Distinguish each node with both IP and Port

- app/platform/fabric/config.json
- app/platform/fabric/gateway/FabricGateway.ts
- app/test/FabricGateway.test.ts
- app/test/SyncService.test.ts
https://jira.hyperledger.org/browse/BE-853
> BE-853 Resolve race condition of discovery request

- CHANGELOG.md
- README.md
- client/package.json
- package.json
- release_notes/v1.1.4.md
> BE-854 v1.1.4 release

- README.md
> BE-854 v1.1.4 release (2)

- CONFIG-OPERATIONS-SERVICE-HLEXPLORER.md
- README.md
- ci/azure-pipelines.yml
- docs/README.md
- docs/project_lifecycle/Incubation.md
- docs/source/CONTRIBUTING.rst
- docs/source/architecture/databaselayer.rst
- docs/source/architecture/dbservices.rst
- docs/source/architecture/gateway.rst
- docs/source/architecture/sync_configuration.rst
- docs/source/architecture/synchronizer.rst
- docs/source/architecture/webserver.rst
- docs/source/dev-setup/azure.rst
- docs/source/dev-setup/devenv.rst
- docs/source/getting_started.rst
- docs/source/presentation/index.rst
- examples/net1/README.md
Readthedocs site has already been updated to `main` branch.
https://blockchain-explorer.readthedocs.io/en/main
> Change default branch to main

- client/package.json
- client/src/components/Header/HeaderView.js
> Fix layout of icons on navigation bar

- Dockerfile
- app/platform/fabric/e2e-test/runTestSuite.sh
- app/platform/fabric/e2e-test/specs/apitest-network-spec-v2.yml
- app/platform/fabric/e2e-test/specs/apitest-network-spec.yml
- app/platform/fabric/sync/SyncService.ts
- app/test/SyncService.test.ts
- client/e2e-test/gui-e2e-test-start.sh
- client/e2e-test/specs/gui-e2e-test-network-spec-v2.yml
- client/e2e-test/specs/gui-e2e-test-network-spec.yml
- client/package-lock.json
- package-lock.json
Upgraded Explorer to support Fabric v2.3.1/1.4.11
Added null validation of last_update payload.
> Be 862 Fix sync error 

- CHANGELOG.md
- README.md
- client/package.json
- client/src/FabricVersion.js
- package.json
- release_notes/v1.1.5.md
> BE-866 Release v1.1.5

- MAINTAINERS.md
Signed-off-by: Jeeva <jsankarapandian@devx.systems>
> Added new maintainer name

- app/rest/dbroutes.ts
- client/package-lock.json
- package-lock.json
> Update fabric-sdk-node to v2.2.6

- client/src/components/Header/HeaderView.js
In small screen size, the icon layout in the header gets broken. To resolve this issue, changed icon layout in the header to reduce icons which are always displaying.
> BE-871 Introduce dropdown to put together icons

- CHANGELOG.md
- README.md
- client/package.json
- package.json
- release_notes/v1.1.6.md
> BE-872 Release v1.1.6

- app/platform/fabric/connection-profile/test-network.json
- app/platform/fabric/gateway/FabricGateway.ts
- examples/net1/connection-profile/test-network.json
- package-lock.json
This change allows non-admin client credential to bring up Explorer instance. And also updated fabric-network package to v2.2.7
https://jira.hyperledger.org/browse/BE-857
> BE-857 Change invoking function of lifecycle scc to get CC info

- README.md
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>
> docs: add code snippet for admin cert modification

- CHANGELOG.md
- README.md
- client/package.json
- package.json
- release_notes/v1.1.7.md
> BE-879 Release v1.1.7

- NOTICE
Signed-off-by: Jeeva <jeevasang@gmail.com>
> Added Notice file

- README.md
Hey,
we found the tutorial super confusing so I tried to make it more clear for another devs.
As the bonus I used my premium grammarly to polish some stuff
> Docs polish
