app/test/package.json
ci/azure-pipelines.yml

This change merges the Cobertura code coverage reports for /app/test and client and publishes them as part of the AZP pipeline
Signed-off-by: Brett Logan <Brett.T.Logan@ibm.com>

[BE-709] Add code coverage report to AZP

---

README.md

Update environment variable "CORE_PEER_GOSSIP_EXTERNAL_ENDPOINT" to be "CORE_PEER_GOSSIP_EXTERNALENDPOINT"

[BE-718] Fix env variable `CORE_PEER_GOSSIP_EXTERNALENDPOINT` in README.md	

---

README.md
app/Explorer.js
app/persistence/fabric/CRUDService.js
lgtm.yml
package-lock.json
package.json

* excluding warnings
* fix rate limit error

BE-717 Code quality fix

---

app/rest/dbroutes.js
app/rest/requestutils.js
app/test/fixtures/reqMultiOrgs.json
app/test/fixtures/reqNoOrgs.json
app/test/fixtures/reqOneOrg.json
app/test/requestutils.js
lgtm.yml
package-lock.json
package.json

BE-719 Fix parameter tampering

---

README.md
TROUBLESHOOT.md

* added javascript scan alert badge

BE-722 Update troubleshoot doc

---

README.md
package.json

Aligned the range of supported Node.js version with the range of fabric SDK packages
https://hyperledger.github.io/fabric-sdk-node/release-1.4/#toc4__anchor

BE-738 Update info regarding required environment

---

TROUBLESHOOT.md
app/platform/fabric/Platform.js
app/platform/fabric/connection-profile/first-network.json
app/platform/fabric/e2e-test/configs/connection-profile/org1-network.json
app/platform/fabric/e2e-test/configs/connection-profile/org2-network.json
app/platform/fabric/sync/SyncPlatform.js
app/platform/fabric/utils/FabricUtils.js
client/e2e-test/configs/connection-profile/org1-network-for-guitest.json
examples/net1/README.md
examples/net1/connection-profile/first-network.json

The `network_config` comming into `setAminEnrolmentPath` and `setEnrolmentPath` are not used beacuse they do not actually have `organizations`.
Therefore, `fullpath` is an unnecessary option.
Delete everything related to the `fullpath`.
Signed-off-by: Sol Kang <pdpxpd@gmail.com>

[BE-741] Remove fullpath option with function

---

app/platform/fabric/Platform.js

The name and the position of the object are reversed and this is not displayed properly.
Signed-off-by: Sol Kang <pdpxpd@gmail.com>

Fix variable position in logger

---

Dockerfile

Chnaged alpine versin of node base image from 3.11 to 3.9
https://jira.hyperledger.org/browse/BE-743

BE-743 Fix segfault in Explorer container

---

app/persistence/fabric/postgreSQL/db/explorerpg.sql

it is common that peer names in amazon managed blockchain network will be long alphanumeric strings. so, database rows length should be set high to make explorer to compatible for Amazon managed blockchain.
[Jira Discussion](https://jira.hyperledger.org/browse/BE-744)
Signed-off by Salmandabbakuti <Salmandabbakuti@github.com>

Making Hyperledger Explorer compatible to Amazon Managed Blockchain Network

---

app/platform/fabric/FabricConfig.js
app/platform/fabric/gateway/FabricGateway.js

* I changed return value to return only one organization
* Standard of return value is the value in config.client.organization
Signed-off-by: 5pecia1 <pdpxpd@gmail.com>

[BE-742] Fix return value about getOrganizationsConfig

---

.eslintrc.json
app/platform/fabric/FabricClient.js
app/platform/fabric/gateway/FabricGateway.js
app/platform/fabric/sync/FabricEvent.js
app/platform/fabric/sync/SyncService.js

The function for querying channels to fabric network has not been supported in the sdk for fabric v2.x. So we need to implement this function by accessing fabric network directly.
This PR will change to use configuration system chaincode to query channels that specified peer is joining.

BE-746 Implement queryChannels by invoke "GetChannels" func in CSCC

---

app/platform/fabric/FabricClient.js
app/platform/fabric/Proxy.js
app/platform/fabric/gateway/FabricGateway.js
app/platform/fabric/sync/SyncService.js

The function for querying block to fabric network has not been supported in the sdk for fabric v2.x. So we need to implement this function by accessing fabric network directly.
This PR will change to use system chaincode for querying channel/block/transaction (qscc) of specified channel.

Implement queryBlock by using system chaincode for query (qscc)

---

app/platform/fabric/FabricClient.js
app/platform/fabric/e2e-test/specs/apitest_test.go
app/platform/fabric/gateway/FabricGateway.js
app/platform/fabric/sync/FabricEvent.js
app/platform/fabric/sync/SyncService.js

Removed accesses to orderer for retrieving genesis block. Use queryBlock for it instead.

BE-752 Retrieve genesis block from peers, not orderer

---

.sonarcloud.properties

To exclude test files from focus of code analysis on SonarCloud.
https://sonarcloud.io/dashboard?id=hyperledger_blockchain-explorer

Add configuration for SonarCloud to narrow focus

---

app/platform/fabric/FabricClient.js
app/platform/fabric/FabricConfig.js
app/platform/fabric/Proxy.js
app/platform/fabric/gateway/FabricGateway.js
app/platform/fabric/sync/SyncService.js

In fabric v2.1.0, when updating txcount of chaincode in explorer, explorer figures out which records should be updated by channel name and chaincode name included in each transaction. Currently chaincode name on chaincodes table is including not only name but also version and ID. So explorer can't find any records to be updated when receiving transactions.
https://jira.hyperledger.org/browse/BE-756

BE-756 Fix tx count in Chaincode view

---

app/platform/fabric/e2e-test/specs/apitest_test.go
app/platform/fabric/gateway/FabricGateway.js

When enabling CA server in network profile, admin certificate is retrieved from CA server instead of using the certificate specified in the network profile. But the certificate retrieved from CA server does not have admin priviledge so explorer running under the certificate fails to query chaincode on the network. Because the query to the installed chaincode is required admin policy by default. Our CA server support has been incomplete yet, so we'll disable this functionality temporarily.
https://jira.hyperledger.org/browse/BE-757

BE-757 Disable CA server support

---

app/persistence/fabric/CRUDService.js
app/persistence/fabric/MetricService.js
app/platform/fabric/FabricClient.js
app/platform/fabric/FabricConfig.js
app/platform/fabric/Platform.js
app/platform/fabric/Proxy.js
app/platform/fabric/gateway/FabricGateway.js

https://jira.hyperledger.org/browse/BE-758

BE-758 Fix channel switch issue on dashboard

---

CHANGELOG.md
client/package-lock.json
client/package.json
client/src/FabricVersion.js
package.json
release_notes/v1.1.0.md

Fixed 1 high vulnerability in client/package.json.
We'll provide the following caveat in the release note on Github release page.
* Peers array for organisation is now mandatory in a connection profile as follow
[e.g. app/platform/fabric/connection-profile/first-network.json](https://github.com/hyperledger/blockchain-explorer/blob/8600c891c53b1ffb72c8f296827b4276669fa954/app/platform/fabric/connection-profile/first-network.json#L42)
* If you have already had existing wallet for the previous version of Explorer, you need to migrate your wallet with the steps described in the following page
[Step for fabric wallet migration](https://hyperledger.github.io/fabric-sdk-node/master/tutorial-migration.html)

BE-770 v1.1.0 release

---

app/platform/fabric/FabricClient.js
app/platform/fabric/FabricConfig.js
app/platform/fabric/connection-profile/first-network.json
app/platform/fabric/e2e-test/configs/connection-profile/org1-network.json
app/platform/fabric/e2e-test/configs/connection-profile/org2-network.json
app/platform/fabric/e2e-test/specs/apitest_test.go
app/platform/fabric/gateway/FabricGateway.js
client/e2e-test/configs/connection-profile/org1-network-for-guitest.json

When specifying certificateAuthorities in connection profile,
generate certificates for admin user to access fabric network
using Fabric CA.
https://jira.hyperledger.org/browse/BE-773

BE-773 Add Fabric CA support

---

app/common/ExplorerMessage.js
app/platform/fabric/FabricClient.js
app/platform/fabric/FabricConfig.js
app/platform/fabric/e2e-test/configs/config_single-pem.json
app/platform/fabric/e2e-test/configs/connection-profile/org1-network-pem.json
app/platform/fabric/e2e-test/specs/apitest_suite_test.go
app/platform/fabric/e2e-test/specs/apitest_test.go
app/platform/fabric/e2e-test/specs/runexplorer.sh
app/platform/fabric/e2e-test/specs/stopexplorer.sh
app/platform/fabric/gateway/FabricGateway.js
app/platform/fabric/sync/SyncService.js

https://jira.hyperledger.org/browse/BE-774
Currently Explorer only supports configuring PEM file path in connection profile. But in practical, some of blockchain managed service provides connection profile including PEM string format to users. Explorer needs to support both formats in connection profile.
https://chat.hyperledger.org/channel/hyperledger-explorer?msg=NJfNtY7PvWxMYvJu6
https://stackoverflow.com/q/62801495/8874164

BE-774 Add pem format support

---

app/platform/fabric/e2e-test/configs/connection-profile/org1-network.json
app/platform/fabric/gateway/FabricGateway.js

When configuring clientTlsIdentity in the connection profile, the ID is added to the connect option.
https://jira.hyperledger.org/browse/BE-768

BE-768 Add mTLS ID to gateway connect option

---

app/platform/fabric/gateway/FabricGateway.js

The documented variable `DISCOVERY_AS_LOCALHOST` seems to ignored when running discovery service.
The `asLocalhost` option is hardcoded to `true`.
This PR makes the discovery service use the value configured during `initialize()`

Use FabricGateway's "asLocalhost" when running discovery service

---

.dockerignore
Dockerfile

With the following changes to Dockerfile, reduce container image size from 942MB (compressed size on docker hub : 425MB) to less than 200MB.
* Use Multi-Stage Docker Builds
To avoid including unnecessary dependencies in the image
* Add some entries to .dockerignore
* Install only packages for production
* Prune unnecessary files by using node-prune tool
* Delete some large files manually
```
REPOSITORY             TAG                 IMAGE ID            CREATED              SIZE
hyperledger/explorer   latest              f1de39318a39        About a minute ago   166MB
hyperledger/explorer   1.1.1               35cf1f510efc        20 hours ago         942MB
```
https://jira.hyperledger.org/browse/BE-779

BE-779 Reduce container image size

---

README-CONFIG.md
app/platform/fabric/FabricConfig.js
app/platform/fabric/sync/SyncService.js

BE-790 Change default encode of value in TX details

---

app/middleware/auth-check.js
app/platform/fabric/Platform.js
app/platform/fabric/rest/adminroutes.js
app/platform/fabric/service/UserService.js

"admin" means as follow
* User specified with client.adminCredential in each connection profile
* User registered with 'admin' role by using user register API
The "admin" user can manage (register/unregister/list user) only for users in
the organization the admin belongs.
At the moment, the GUI interface for registering user on Explorer will
be showing even if you login with non admin user, but actual operations
(e.g. registering a new user) should be refused.

BE-792 Allow only "admin" to manage user

---

app/persistence/fabric/CRUDService.js
app/platform/fabric/FabricClient.js
app/platform/fabric/FabricConfig.js
app/platform/fabric/Platform.js
app/platform/fabric/Proxy.js
app/platform/fabric/config.json
app/platform/fabric/connection-profile/first-network.json
app/platform/fabric/e2e-test/configs/config_multi.json
app/platform/fabric/e2e-test/specs/apitest_def_test.go
app/platform/fabric/e2e-test/specs/apitest_test.go
app/platform/fabric/gateway/FabricGateway.js
app/platform/fabric/service/NetworkService.js
app/platform/fabric/sync/SyncPlatform.js
app/platform/fabric/sync/SyncService.js
app/platform/fabric/utils/FabricUtils.js
client/src/components/Login/Login.js

Fixed to use only network ID for managing state internally (network Name is used only for showing network name on Login view)
```json
app/platform/fabric/config.json
{
"network-configs": {
"first-network": {  <===[Network-ID]
"name": "My first network",   <===[Network-Name]
"profile": "./connection-profile/first-network.json"
}
},
"license": "Apache-2.0"
}
```
The name in a connection profile is not used any purpose.
```json
app/platform/fabric/connection-profile/first-network.json
{
"name": "first network (ignored)",   <===[NotUsed]
"version": "1.0.0",
"license": "Apache-2.0",
"client": {
"tlsEnable": true,
```

BE-814 Fix inconsistency of network key

---

app/platform/fabric/sync/SyncService.js

As explained in BE-828 and RocketChat.

BE-828 Fix transaction timestamps

---

CHANGELOG.md
README.md
client/package-lock.json
client/package.json
package-lock.json
package.json
release_notes/v1.1.3.md

BE-832 v1.1.3 release

---

app/persistence/fabric/CRUDService.ts
app/persistence/fabric/MetricService.ts
app/persistence/postgreSQL/PgService.ts
app/rest/dbroutes.ts
app/rest/requestutils.ts

As described in BE-833. This fixes all SQL injection attack vectors I could find. Let me know if I missed any queries.
It makes the code a bit more readable as well (in my opinion). 
Signed-off-by: sigma67 <benedikt.putz@wiwi.uni-regensburg.de>

Transform SQL queries to parameterized queries [BE-833]

---

README.md
app/platform/fabric/FabricConfig.ts
app/platform/fabric/gateway/FabricGateway.ts

solved this error [BE-840]
Signed-off-by: myeongkil clevermk7211@gmail.com

[BE-840] Fix discovery error on mutual TLS

---

README.md

change 'master' to 'latest' in the url (master does not point to any existing page)

Fix url of the fabric official tuto

---

README.md
app/platform/fabric/e2e-test/docker-compose.yaml
docker-compose.yaml

Signed-off-by: Binoy Mathew <binoy123@gmail.com>
This is to fix https://jira.hyperledger.org/browse/BE-848

[BE-848] Update walletstore location in docker-compose files

---

app/platform/fabric/sync/SyncService.ts
app/test/FabricGateway.test.ts
app/test/SyncService.test.ts
app/test/block.json
app/test/block_config.json

* Also added computation of ID for config TX to serve as a reference for the API & frontend. (Normally config tx doesn't have its tx id).
* Added test cases for processBlockEvent method in SyncServices class.

BE-852 Fix to get RWset for config TX synced correctly

---

README-CONFIG.md

BE-801 Add the steps for configuring a subdomain to README-CONFIG.md

---

Dockerfile

The current node version (10.19-alpine3.9) has some vulnerabilities. Please refer the following JIRA for detail.
https://jira.hyperledger.org/browse/BE-858

BE-858 Upgrade base image of Explorer container image

---

main.sh

As mentioned on RocketChat, running tsc is mandatory now before one can start the backend with start.sh
I added the tsc step with npm run build in main.sh
Signed-off-by: sigma67 <benedikt.putz@wiwi.uni-regensburg.de>

add typescript compilation on main.sh install

---

.eslintrc.json
app/platform/fabric/sync/FabricEvent.ts
app/platform/fabric/sync/SyncPlatform.ts
app/platform/fabric/sync/SyncService.ts
app/test/SyncService.test.ts
client/e2e-test/startnetwork.js

This change includes:
* Fixed unintended asynchronous function calls
* Change block synchronization by FabricEvent to start from the current block (Unintentionally multiple block sync processes had been triggered at bootup)
* Introduced immediate invoked function exression (IIFE) into some initialization steps of SyncPlatform 
* Add a step for sync up of chaincode table to synchNetworkConfigToDB method (Some transactions included in block data hadn't been counted as transaction for each chaincode until chaincode table is updated by service discovery )

BE-855 Stop unnecessary sync process triggered by FabricEvent

---

client/src/components/Login/Login.js

- resolves `enableAuthentication:false` setup using wrong network key preventing auto login issue.

Bugfix: disable enableAuthentication auth auto login using wrong network key issue

---

app/platform/fabric/gateway/FabricGateway.ts
app/platform/fabric/sync/SyncService.ts
app/sync.ts
app/test/FabricGateway.test.ts

- resolves `discoveryError` not resetting `waitingResp` flag, causing a `Have already been sending a request` loop.
```
[WARN] FabricGateway - Failed to send discovery request for channel Error: DiscoveryService has failed to return results
at DiscoveryService.send (.../blockchain-explorer/node_modules/fabric-common/lib/DiscoveryService.js:370:10)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
...
[INFO] FabricGateway - Have already been sending a request
[INFO] FabricGateway - Have already been sending a request
[INFO] FabricGateway - Have already been sending a request
[INFO] FabricGateway - Have already been sending a request
[INFO] FabricGateway - Have already been sending a request
```
- resolves `queryChainInfo` timeout error killing explorer.
```
[ERROR] Sync - …
```

Bugfix: timeout error crashing explorer

---

app/sync.ts
client/e2e-test/specs/dashboard/dashboard.test.js

- prevents the explorer from shutting down on `ETIMEOUT` error.
```
[2021-07-21T14:26:47.644] [ERROR] FabricGateway - Failed to get chain info from channel defaultchannel :  FabricError: Query failed. Errors: ["Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: read ETIMEDOUT"]
at SingleQueryHandler.evaluate (.../blockchain-explorer/node_modules/fabric-network/lib/impl/query/singlequeryhandler.js:47:23)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Transaction.evaluate (.../blockchain-explorer/node_modules/fabric-network/lib/transaction.js:276:25)
[2021-07-21T14:26:47.644] [INFO] SyncServices - syncBlocks: Failed to retrieve channelInfo >> defaultchannel
```

bugfix: prevent ETIMEOUT error from shuting down explorer

---

app/platform/fabric/sync/SyncService.ts
app/test/SyncService.test.ts
package-lock.json
package.json

In explorer, you convert `envelope_signature`, `payload_extension`, `creator_nonce`, `input`, `endorser_signature` to Hex with `convertHex.bytesToHex`
`convertHex.bytesToHex` can’t deal with hex include `a` `b` `c` `d` `e`, for example, 
```node
const convertHex = require('convert-hex');
let test = Buffer.from('HELLO');
console.log(test.toString('hex'));
console.log(convertHex.bytesToHex(test));
```
`H` is `48`
`E` is `45`
`L` is `4c`
`O` is `4f`
`HELLO` should be `48454c4c4f`
But when I try to use `convertHex.bytesToHex`, the result is `4845000`. Those hex with `abcde` is converted into `0`
Step1: Add some `console.log` to explore (in commit 7a3caeedae72181c8df54b929b85f7cee2cf6e5d), build a docker image. 
```bash
git checkout 7a3caeedae72181c8df54b929b85f7cee2cf6e5d
docker build -t …
```

Fix: convert-hex can’t convert Buffer to Hex properly

---

app/platform/fabric/FabricClient.ts

File: app/platform/fabric/FabricClient.ts
Error at line ExplorerError because its expecting string
try { 
// Use Gateway to connect to fabric network this.fabricGateway = new FabricGateway(this.config); await this.fabricGateway.initialize(); }
catch (error) { 
// TODO in case of the failure, should terminate explorer? 
logger.error(error); *throw new ExplorerError(error);* 
}

BE-984 - fixed throw ExplorerError in FabricClient.ts

---

app/common/helper.ts

The log option 'daysToKeep' is deprecated without any replacement available. Suggested change is to use `numBackups`; unfortunately, `maxLogSize` generates an unpredictable number of logs per time, so ensuring that a full week of logs is retained is incompatible with the migration. (A possible workaround would be setting `numBackups: 1000000000`, or some other ludicrously-high value, but even this isn't perfectly guaranteed to include a full week if something goes wrong that generates a massive amount of logs.)
This change will eventually be necessary. Currently it is not, but leaving the deprecation present generates a long list of warnings when built (true since #272); this will suppress those.

daysToKeep deprecation - keep daily logs

---

README.md

Commands and portions of results are different on Linux vs. MacOS, and this is not reflected in the docs. Updated to correct that.
Also, add a small piece explaining how to generate a new Docker image from this repository. It already doesn't use the same name as the canonical image (`hyperledger-explorer` rather than `hyperledger/explorer`), so this is not going to pollute the image repository and is unlikely to cause confusion unless someone deliberately tries to mess with it.
The second part is useful for developers who want to test changes to the image and/or create forks of the project. It would have saved me some time - I made an unwarranted assumption about the local install/build process also creating images and took a while to correct that.

Customize Quick-Start docs by OS

---

README.md
app/exportConfig.sh
start.sh

- script that exports DB settings from `app/explorerconfig.json` to the envvars, which makes it easier to use the example commands in the Quick Start
- script and doc tweaks to make it clear that `npm start` runs the app only while the process continues rather than in detached mode

Two small tweaks for ease of use

---

Dockerfile

Follow-up for #301; not useful if that is rejected.
There doesn't seem to be a good way to make this respect a param or
envvar passed in, and it's not strictly *needed* if you're mapping ports.
Having it be present & incorrect in some cases is worse than having it
be absent in some cases where it would be correct. So just drop it
entirely.

Drop EXPOSE from Dockerfile

---

.github/ISSUE_TEMPLATE/bug-report.yaml
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/enhancement.yaml
.github/PULL_REQUEST_TEMPLATE.md

Signed-off-by: Aditya Joshi <adityaprakashjoshi1@gmail.com>
Added gitHub forms for bugs and enhancement issues

Use github forms for issue templates
